import glob
import os

BuildDir('debug', '.', duplicate=0)
BuildDir('release', '.', duplicate=0)

Import('libbsgstl_d libbsgstl')

src_files = glob.glob('*.cpp')

debug_files = [os.path.join('debug', x) for x in src_files]
release_files = [os.path.join('release', x) for x in src_files]

includes = ['/usr/include/python2.5',
		'../bs_gstl/include',
		'../bs_gstl/src',
		'../tnt_126',
		'/opt/boost_1_38_src'];

hpgl_d_so = SharedLibrary('hpgl_d', debug_files,
	CPPPATH=includes,
	CPPDEFINES=['DEBUG', 'BS_GSTL_EXPORTS', 'BS_EXPORINTG_PLUGIN', 'BS_PROPERTY_ARRAY_EXPORTS', 'BS_PROPERTY_SERVER_EXPORTS'],
	CCFLAGS='-ggdb -fPIC',
	LIBS=['libboost_python-mt-d-py2.5',
		libbsgstl_d],
	LIBPATH=['../bs_gstl', '/opt/boost_1_38_builded_fPIC/']
	)


hpgl_so = SharedLibrary('hpgl', release_files,
	CPPPATH=includes,
	CPPDEFINES=['NDEBUG', 'BS_GSTL_EXPORTS', 'BS_EXPORINTG_PLUGIN', 'BS_PROPERTY_ARRAY_EXPORTS', 'BS_PROPERTY_SERVER_EXPORTS'],
	CCFLAGS='-g -O3 -finline-functions -fmove-loop-invariants -fopenmp',
        LIBS=['libboost_python-mt-py2.5',
                'libgomp',
		libbsgstl
                ],
	LIBPATH=['../bs_gstl', '/opt/boost_1_38_builded_fPIC/']
	)

Return ('hpgl_d_so', 'hpgl_so')
