######################################################################
# Automatically generated by qmake (1.03a) Tue Mar 11 18:12:29 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += cartesian_grid.h geovalue.h location.h neighborhood.h non_param_cdf.h
SOURCES += benchmark1.cc \
           cartesian_grid.cc \
           geovalue.cc 
TARGET = benchmark1

INCLUDEPATH += ../../
